language: cpp
compiler:  
    - gcc
    - clang
os:
    - linux


matrix:
  include:

    # Build with Linux and gcc.
    # The default gcc compiler does not support C++11 so install a higher version.
    - os: linux
      env: CC=gcc-5 CXX=g++-5
      addons: &gcc5
        apt:
          packages:
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-5
        - sudo apt-get install -y libboost-test-dev
        - sudo apt-get install -y libboost-system-dev
        - sudo apt-get install -y libboost-filesystem-dev


before_script:  
    - cmake .
script: make  

addons:
  apt:
    sources:
      # For cmake >= 2.8.8 (for CMakePackageConfigHelpers)
      - boost-latest
    packages:
      - cmake
      - libboost-dev
      
after_success:
  # Generate the docs only if main, the travis_build_docs is true and we can use secure variables
  - >-
    if [[ "$TRAVIS_BRANCH" = "main" && -n "$TRAVIS_BUILD_DOCS" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then
      cd $PROJECT_DIR_ABS
      source .ci/setup-ssh.sh || travis_terminate 1
      .ci/generateDocumentation.sh || travis_terminate 1
    fi
