language: cpp

compiler:  
    - gcc
    - clang

before_script:  
    - mkdir build
    - cd build
    - cmake ..

script: make  

addons:
  apt:
    sources:
      # For cmake >= 2.8.8 (for CMakePackageConfigHelpers)
      - boost-latest
    packages:
      - cmake
      - libboost-dev



